security:
  oauth2:
    client:
      clientId: service-account
      clientSecret: ${SERVICE_ACCOUNT_PASSWORD}
      accessTokenUri: http://service-auth:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
    url: jdbc:mysql://service-account-db/account
    username: ${SERVICE_ACCOUNT_DB_USER}
    password: ${SERVICE_ACCOUNT_DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

flyway:
  url: jdbc:mysql://service-account-db:3306/account
  user: ${SERVICE_ACCOUNT_DB_USER}
  password: ${SERVICE_ACCOUNT_DB_PASSWORD}
  locations: classpath:db/migration
  enabled: true

server:
  context-path: /accounts
  port: 6000

grpc:
  port: 6565

eureka:
    instance:
        nonSecurePort: 6565